### ISSUE TITLE
Rasterscan Loop

### ISSUE THREAD

**Issue by lilliangreenough** [StevenJohnsonOptics/Single-Pixel-Imaging#2]
Hello,

I have been looking at it for a few days now and I am struggling to work the code to simulate a rasterscan, especially the indexing for a section of the image for the loop, since the variable obj_Vector is a long array. Could you help me in indexing the array for the loop? I think I am getting my variables mixed up, is it obj_Vector that we want to take sections of to process?

Thank you, Lillian

**Comment by StevenJohnsonOptics** [comment]
The simple step is replacing 'hadamard' with 'np.identity'. This will use the identity matrix instead. The obj_Vector is the picture in a single vector. It would be possible to reshape the vector and reshape the sampling pattern (see code added to repo).

**Comment by lilliangreenough** [comment]
Thank you, I'd changed it to the identity matrix already, I was more stuck on including it within the loop.
